/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package us.frankkelly.soccer;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.TreeMap;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * TODO
 * Players per Rotation = Half the bench
 * Different Assignment strategies
 *  Time per player
 *  Strongest First Half
 *  Add random factor
 *  Alternate Front/Back in 2nd Half
 */
public class App {
    
    private static final int GOALIE = 1;
    private static final int ELEVEN_VS_ELEVEN = 11;
    private List<Player> team;
    private Player firstHalfGoalie, secondHalfGoalie;
    private int lengthOfGameInMinutes=70, rotationsPerHalf=5, playersPerRotation=3;
    private Map<String,Integer> timePerPlayer = new TreeMap<>();

    public static void main(String[] args) {
        new App();
    }
    
    public App() {
        try {
            team = loadTeamFromClasspath( "gr78-red.csv");
            loadPreferences();
            calculateRotationForGame(team, firstHalfGoalie, secondHalfGoalie);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void loadPreferences() {        
        System.out.println("Enter Player # for Goalie for 1st Half: ");
        Scanner scanner = new Scanner(System.in);
        int i = scanner.nextInt();
        firstHalfGoalie = team.get(i-1);
        System.out.println("Goalie for 1st Half: " + firstHalfGoalie.getName());
        
        System.out.println("Enter Player # for Goalie for 2nd Half: ");
        scanner = new Scanner(System.in);
        i = scanner.nextInt();
        secondHalfGoalie = team.get(i-1);
        System.out.println("Goalie for 2nd Half: " + secondHalfGoalie.getName());
        scanner.close();
    }
    
    public void calculateRotationForGame(List<Player> team, Player goalie1, Player goalie2) {
        List<Player> fullTeamCopy = new ArrayList<>(team);
        List<Player> teamRemaining = new ArrayList<>(team);
        
        //First Half
        System.out.println("===============");
        System.out.println("= ROTATIONS   =");
        System.out.println("===============");
        int timePerRotation =  lengthOfGameInMinutes/(rotationsPerHalf*2);
        int gameTime = 0;
        
        System.out.println("************");
        System.out.println("* 1ST HALF *");
        System.out.println("************");
        Rotation433 firstHalfRotation = new Rotation433();
        firstHalfRotation.setGoalie(goalie1);
        fullTeamCopy.remove(goalie1);
        teamRemaining.remove(goalie1);
        
        //Create initial Rotation
        for(int i=0; i< ELEVEN_VS_ELEVEN - GOALIE; i++) {
            Player p = fullTeamCopy.get(i);
            firstHalfRotation.addPlayer(p); 
            teamRemaining.remove(p);
        }
        firstHalfRotation.print(1, gameTime, gameTime += timePerRotation);
        printTeam("Available / Resting", teamRemaining);
        printSeparator();        
        
        //Create Rotations
        for(int i=2; i<= rotationsPerHalf; i++) {
            recordPlayingTime(firstHalfRotation, timePerRotation);
            for(int j=0; j< playersPerRotation; j++) {
                Player replaced = firstHalfRotation.replacePlayer(teamRemaining.get(0));
                teamRemaining.remove(0);
                teamRemaining.add(replaced);
            }
            
            firstHalfRotation.print(i, gameTime, gameTime += timePerRotation);
            printTeam("Available / Resting", teamRemaining);
            printSeparator();
        }
        //Record last rotation playing time
        recordPlayingTime(firstHalfRotation, (lengthOfGameInMinutes/2)-gameTime);
        printPlayingTime();
        firstHalfRotation = null;
        
        //Second Half
        System.out.println("************");
        System.out.println("* 2ND HALF *");
        System.out.println("************");
        gameTime = lengthOfGameInMinutes/2;

        Rotation433 secondHalfRotation = new Rotation433();
        teamRemaining = new ArrayList<>(team);
        secondHalfRotation.setGoalie(goalie2);
        fullTeamCopy.remove(goalie2);
        teamRemaining.remove(goalie2);
        for(int i=0; i< ELEVEN_VS_ELEVEN - GOALIE; i++) {
            Player p = fullTeamCopy.get((fullTeamCopy.size()-1)-i);
            secondHalfRotation.addPlayer(p); 
            teamRemaining.remove(p);
        }
        secondHalfRotation.print(1, gameTime, gameTime += timePerRotation);
        printTeam("Available / Resting", teamRemaining);
        printSeparator();
        
        //Create Rotations
        for(int i=2; i<= rotationsPerHalf; i++) {
            recordPlayingTime(secondHalfRotation, timePerRotation);
            for(int j=0; j< playersPerRotation; j++) {
                Player replaced = secondHalfRotation.replacePlayer(teamRemaining.get(0));
                teamRemaining.remove(0);
                teamRemaining.add(replaced);
            }
            secondHalfRotation.print(i, gameTime, gameTime += timePerRotation);
            printTeam("Available / Resting", teamRemaining);
            printSeparator();
        }
        //Record last rotation playing time
        recordPlayingTime(secondHalfRotation, lengthOfGameInMinutes-gameTime);
        
        printPlayingTime();
    }
    
    private void printPlayingTime() {      
        printSeparator();
        System.out.println("* PLAYING TIME TOTALS *");
        for(Map.Entry<String, Integer> entry : timePerPlayer.entrySet()) {
            System.out.println(entry.getKey() + " --> " + entry.getValue() + " mins");
        }
        printSeparator();
    }

    private void recordPlayingTime(Rotation r, int playingTime) {
        for (String s : r.getPlayerNames()) {
            if (!timePerPlayer.containsKey(s)) {
                timePerPlayer.put(s, playingTime);
            } else {
                int earlierTime = timePerPlayer.get(s);
                timePerPlayer.put(s, earlierTime + playingTime);
            }
        }
        
        //printPlayingTime();
    }

    private void printSeparator() {
        System.out.println("-----------------------------------------");
        
    }

    private void printTeam(String s, List<Player> list) {
        System.out.println(s);
        for(Player p : list) {
            System.out.println(" " + p.getName() + " " + p.getScore());
        }
    }
    
    private List<Player> loadTeamFromClasspath(String fileName) throws Exception {
        Path path = Paths.get(getClass().getClassLoader().getResource(fileName).toURI());

        Stream<String> stream = Files.lines(path);

        List<Player> list = stream.map(Player::getPlayer).collect(Collectors.toList());
        stream.close();
        Collections.sort(list);

        int i = 1;
        for (Player p : list) {
            System.out.println("Player #" + i++ + ") " + p.getName() + " " + p.getScore());
        }
        
        return Collections.unmodifiableList(list);
    }
}
